// <auto-generated />
using System;
using AgentCfo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentCfo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627154150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentCfo.Core.Entities.AgentDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverriddenBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid?>("RelatedBudgetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RelatedBudgetId");

                    b.HasIndex("RelatedTransactionId");

                    b.ToTable("AgentDecisions");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<string>("AfterState")
                        .HasColumnType("text");

                    b.Property<string>("BeforeState")
                        .HasColumnType("text");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertThresholdPercent")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HardLimit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Category")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunwayDays")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RunwayEndDate")
                        .HasColumnType("date");

                    b.Property<string>("Scenario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RunwayThresholdDays")
                        .HasColumnType("integer");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "OccurredAt");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.AgentDecision", b =>
                {
                    b.HasOne("AgentCfo.Core.Entities.Organization", "Organization")
                        .WithMany("Decisions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgentCfo.Core.Entities.Budget", "RelatedBudget")
                        .WithMany()
                        .HasForeignKey("RelatedBudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgentCfo.Core.Entities.Transaction", "RelatedTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("RelatedBudget");

                    b.Navigation("RelatedTransaction");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.AuditEntry", b =>
                {
                    b.HasOne("AgentCfo.Core.Entities.Organization", "Organization")
                        .WithMany("AuditEntries")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Budget", b =>
                {
                    b.HasOne("AgentCfo.Core.Entities.Organization", "Organization")
                        .WithMany("Budgets")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AgentCfo.Core.Common.Money", "CurrentSpend", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("BudgetId");

                            b1.ToTable("Budgets");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");
                        });

                    b.OwnsOne("AgentCfo.Core.Common.Money", "MonthlyLimit", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("BudgetId");

                            b1.ToTable("Budgets");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");
                        });

                    b.Navigation("CurrentSpend")
                        .IsRequired();

                    b.Navigation("MonthlyLimit")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Forecast", b =>
                {
                    b.HasOne("AgentCfo.Core.Entities.Organization", "Organization")
                        .WithMany("Forecasts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AgentCfo.Core.Common.Money", "CurrentCashBalance", b1 =>
                        {
                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("ForecastId");

                            b1.ToTable("Forecasts");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");
                        });

                    b.OwnsOne("AgentCfo.Core.Common.Money", "MonthlyBurnRate", b1 =>
                        {
                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("ForecastId");

                            b1.ToTable("Forecasts");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");
                        });

                    b.OwnsOne("AgentCfo.Core.Common.Money", "MonthlyRevenue", b1 =>
                        {
                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("ForecastId");

                            b1.ToTable("Forecasts");

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");
                        });

                    b.OwnsMany("AgentCfo.Core.Entities.ProjectionPoint", "ProjectionPoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("ForecastId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ForecastId");

                            b1.ToTable("ProjectionPoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ForecastId");

                            b1.OwnsOne("AgentCfo.Core.Common.Money", "ProjectedBalance", b2 =>
                                {
                                    b2.Property<Guid>("ProjectionPointId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)");

                                    b2.HasKey("ProjectionPointId");

                                    b2.ToTable("ProjectionPoints");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectionPointId");
                                });

                            b1.OwnsOne("AgentCfo.Core.Common.Money", "ProjectedExpenses", b2 =>
                                {
                                    b2.Property<Guid>("ProjectionPointId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)");

                                    b2.HasKey("ProjectionPointId");

                                    b2.ToTable("ProjectionPoints");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectionPointId");
                                });

                            b1.OwnsOne("AgentCfo.Core.Common.Money", "ProjectedRevenue", b2 =>
                                {
                                    b2.Property<Guid>("ProjectionPointId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)");

                                    b2.HasKey("ProjectionPointId");

                                    b2.ToTable("ProjectionPoints");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectionPointId");
                                });

                            b1.Navigation("ProjectedBalance")
                                .IsRequired();

                            b1.Navigation("ProjectedExpenses")
                                .IsRequired();

                            b1.Navigation("ProjectedRevenue")
                                .IsRequired();
                        });

                    b.Navigation("CurrentCashBalance")
                        .IsRequired();

                    b.Navigation("MonthlyBurnRate")
                        .IsRequired();

                    b.Navigation("MonthlyRevenue")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("ProjectionPoints");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Organization", b =>
                {
                    b.OwnsOne("AgentCfo.Core.Common.Money", "MonthlyBudget", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("MonthlyBudget")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Transaction", b =>
                {
                    b.HasOne("AgentCfo.Core.Entities.Organization", "Organization")
                        .WithMany("Transactions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AgentCfo.Core.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AgentCfo.Core.Entities.Organization", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Budgets");

                    b.Navigation("Decisions");

                    b.Navigation("Forecasts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
