import { useState } from 'react';
import { FileText, ChevronDown, ChevronUp, Loader2 } from 'lucide-react';
import { api } from '../api/client';

interface FinancialSummaryProps {
  orgId: string;
}

export function FinancialSummary({ orgId }: FinancialSummaryProps) {
  const [expanded, setExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await api.generateSummary(orgId);
      setSummary(result.summary);
      setExpanded(true);
    } catch (err) {
      console.error('Failed to generate summary:', err);
    } finally {
      setLoading(false);
    }
  };

  if (!summary) {
    return (
      <button
        onClick={handleGenerate}
        disabled={loading}
        className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-800 border border-blue-500/20 hover:bg-blue-400/10 rounded-lg text-xs font-medium text-gray-300 transition-colors disabled:opacity-40"
      >
        {loading ? (
          <Loader2 size={12} className="animate-spin text-blue-400" />
        ) : (
          <FileText size={12} className="text-blue-400" />
        )}
        {loading ? 'Generating...' : 'Generate Report'}
      </button>
    );
  }

  return (
    <div className="bg-gray-800 rounded-xl border border-gray-700">
      <button
        onClick={() => setExpanded(prev => !prev)}
        className="w-full px-4 py-3 flex items-center justify-between text-left group"
      >
        <div className="flex items-center gap-2">
          <FileText size={14} className="text-blue-400" />
          <h2 className="text-sm font-semibold text-white">Financial Report</h2>
          <span className="text-xs text-gray-500">Generated by Agent</span>
        </div>
        <span className="text-gray-500 group-hover:text-gray-300 transition-colors">
          {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </span>
      </button>
      {expanded && (
        <div className="px-4 pb-4 border-t border-gray-700 pt-4">
          <pre className="text-xs text-gray-300 whitespace-pre-wrap leading-relaxed font-mono bg-gray-900 rounded-lg p-4 border border-gray-700 max-h-[400px] overflow-y-auto">
            {summary}
          </pre>
        </div>
      )}
    </div>
  );
}
